import pandas as pd
import sqlite3
import json

questions_data = [
    # =========================================================================
    # --- QUANTITATIVE APTITUDE ---
    # =========================================================================
    {
        "id": 1,
        "section": "Aptitude",
        "category": "quantitative",
        "topic": "Time and Work",
        "question": "A can complete a piece of work in 12 days and B can do it in 16 days. They work together for 4 days, then A leaves. How many days will B take alone to finish the remaining work?",
        "option_a": "5 days",
        "option_b": "6.67 days",
        "option_c": "7 days",
        "option_d": "8.33 days",
        "answer": "option_b",
        "difficulty": "Medium",
        "explanation": "Work rate: A = 1/12, B = 1/16. Together in 1 day = 7/48. In 4 days = 28/48 = 7/12. Remaining work = 5/12. Time B takes = (5/12) / (1/16) = 20/3 = 6.67 days."
    },
    {
        "id": 2,
        "section": "Aptitude",
        "category": "quantitative",
        "topic": "Permutations and Combinations",
        "question": "In how many different ways can the letters of the word 'PLACEMENT' be arranged?",
        "option_a": "362880",
        "option_b": "181440",
        "option_c": "90720",
        "option_d": "45360",
        "answer": "option_b",
        "difficulty": "Medium",
        "explanation": "'PLACEMENT' has 9 letters with 'E' repeating twice. Total arrangements = 9! / 2! = 362880 / 2 = 181,440."
    },
    {
        "id": 3,
        "section": "Aptitude",
        "category": "quantitative",
        "topic": "Time, Speed and Distance",
        "question": "A train 150 meters long passes a telegraph pole in 10 seconds. How long will it take to cross a platform 210 meters long?",
        "option_a": "20 seconds",
        "option_b": "24 seconds",
        "option_c": "18 seconds",
        "option_d": "25 seconds",
        "answer": "option_b",
        "difficulty": "Easy",
        "explanation": "Speed = 150m / 10s = 15 m/s. Total distance = 150m + 210m = 360m. Time = 360 / 15 = 24 seconds."
    },
    {
        "id": 4,
        "section": "Aptitude",
        "category": "quantitative",
        "topic": "Percentage",
        "question": "If the price of petrol increases by 25%, by what percentage must a driver reduce petrol consumption so that expenditure remains unchanged?",
        "option_a": "20%",
        "option_b": "25%",
        "option_c": "15%",
        "option_d": "18%",
        "answer": "option_a",
        "difficulty": "Easy",
        "explanation": "Reduction % = [R / (100 + R)] * 100 = [25 / 125] * 100 = 20%."
    },
    {
        "id": 5,
        "section": "Aptitude",
        "category": "quantitative",
        "topic": "Numbers",
        "question": "What is the smallest number which when divided by 12, 16, 24 and 36 leaves a remainder of 7 in each case?",
        "option_a": "144",
        "option_b": "151",
        "option_c": "137",
        "option_d": "161",
        "answer": "option_b",
        "difficulty": "Medium",
        "explanation": "LCM(12, 16, 24, 36) = 144. Required number = LCM + Remainder = 144 + 7 = 151."
    },
    {
        "id": 6,
        "section": "Aptitude",
        "category": "quantitative",
        "topic": "Average",
        "question": "The average weight of 8 men is increased by 2.5 kg when a new man replaces one of them who weighs 65 kg. What is the weight of the new man?",
        "option_a": "75 kg",
        "option_b": "85 kg",
        "option_c": "80 kg",
        "option_d": "90 kg",
        "answer": "option_b",
        "difficulty": "Easy",
        "explanation": "Total weight gain = 8 * 2.5 = 20 kg. Weight of new man = 65 + 20 = 85 kg."
    },
    {
        "id": 7,
        "section": "Aptitude",
        "category": "quantitative",
        "topic": "Profit and Loss",
        "question": "A trader marks an article 30% above the cost price and allows a discount of 15% on the marked price. Find his net profit percentage.",
        "option_a": "10.5%",
        "option_b": "12%",
        "option_c": "15%",
        "option_d": "8.5%",
        "answer": "option_a",
        "difficulty": "Easy",
        "explanation": "Let CP = 100. MP = 130. SP = 130 * 0.85 = 110.5. Profit % = 10.5%."
    },
    {
        "id": 8,
        "section": "Aptitude",
        "category": "quantitative",
        "topic": "Ratio and Proportion",
        "question": "Two numbers are in the ratio 3 : 5. If 9 is subtracted from each, the new numbers are in the ratio 12 : 23. Find the smaller number.",
        "option_a": "33",
        "option_b": "45",
        "option_c": "55",
        "option_d": "27",
        "answer": "option_a",
        "difficulty": "Medium",
        "explanation": "Let numbers be 3x and 5x. (3x - 9)/(5x - 9) = 12/23 => 23(3x - 9) = 12(5x - 9) => 69x - 207 = 60x - 108 => 9x = 99 => x = 11. Smaller number = 3(11) = 33."
    },
    {
        "id": 9,
        "section": "Aptitude",
        "category": "quantitative",
        "topic": "Mixtures",
        "question": "A mixture contains milk and water in the ratio 5 : 1. On adding 5 liters of water, the ratio of milk and water becomes 5 : 2. What is the quantity of milk in the original mixture?",
        "option_a": "15 liters",
        "option_b": "25 liters",
        "option_c": "20 liters",
        "option_d": "30 liters",
        "answer": "option_b",
        "difficulty": "Medium",
        "explanation": "Milk = 5x, Water = x. On adding 5L water: 5x / (x + 5) = 5/2 => 10x = 5x + 25 => 5x = 25 liters of milk."
    },
    {
        "id": 10,
        "section": "Aptitude",
        "category": "quantitative",
        "topic": "Probability",
        "question": "Two dice are thrown simultaneously. What is the probability of getting a sum greater than 9?",
        "option_a": "1/6",
        "option_b": "5/36",
        "option_c": "1/4",
        "option_d": "7/36",
        "answer": "option_a",
        "difficulty": "Medium",
        "explanation": "Sum > 9 means 10 (3 outcomes), 11 (2 outcomes), 12 (1 outcome) = 6 total favorable outcomes. P = 6/36 = 1/6."
    },

    # =========================================================================
    # --- LOGICAL REASONING ---
    # =========================================================================
    {
        "id": 11,
        "section": "Aptitude",
        "category": "logical",
        "topic": "Analogy",
        "question": "Architect : Building :: Sculptor : ?",
        "option_a": "Museum",
        "option_b": "Statue",
        "option_c": "Chisel",
        "option_d": "Stone",
        "answer": "option_b",
        "difficulty": "Easy",
        "explanation": "An Architect creates a Building; similarly a Sculptor creates a Statue."
    },
    {
        "id": 12,
        "section": "Aptitude",
        "category": "logical",
        "topic": "Series (number & alphabet)",
        "question": "Find the missing term in the series: 4, 11, 30, 67, 128, ?",
        "option_a": "219",
        "option_b": "222",
        "option_c": "243",
        "option_d": "256",
        "answer": "option_a",
        "difficulty": "Hard",
        "explanation": "Pattern: n^3 + 3. For n=6: 6^3 + 3 = 216 + 3 = 219."
    },
    {
        "id": 13,
        "section": "Aptitude",
        "category": "logical",
        "topic": "Coding–Decoding",
        "question": "If 'PYTHON' is coded as 'QZEIJM' in a secret pattern, how is 'FLASK' coded?",
        "option_a": "GKZTL",
        "option_b": "GKZRJ",
        "option_c": "GMBTL",
        "option_d": "EKZTJ",
        "answer": "option_a",
        "difficulty": "Easy",
        "explanation": "P(+1)->Q, Y(+1)->Z... Standard character shift gives GKZTL."
    },
    {
        "id": 14,
        "section": "Aptitude",
        "category": "logical",
        "topic": "Blood Relations",
        "question": "Pointing to a photograph, Priya said, 'He is the son of the only daughter of my grandfather.' How is Priya related to the person?",
        "option_a": "Sister",
        "option_b": "Mother",
        "option_c": "Cousin",
        "option_d": "Aunt",
        "answer": "option_a",
        "difficulty": "Medium",
        "explanation": "Grandfather's only daughter = Priya's mother. Her son is Priya's brother. So Priya is his sister."
    },
    {
        "id": 15,
        "section": "Aptitude",
        "category": "logical",
        "topic": "Direction Sense",
        "question": "Rohan walks 10 km North, turns Right and walks 6 km, then turns Right again and walks 10 km. How far and in which direction is he from his starting point?",
        "option_a": "6 km East",
        "option_b": "6 km West",
        "option_c": "10 km East",
        "option_d": "4 km South",
        "answer": "option_a",
        "difficulty": "Easy",
        "explanation": "10km North cancel out 10km South. He is exactly 6 km East of the starting point."
    },
    {
        "id": 16,
        "section": "Aptitude",
        "category": "logical",
        "topic": "Seating Arrangements",
        "question": "Five friends A, B, C, D, E are sitting in a row facing North. A is to the immediate right of B. E is to the left of B but right of C. D is at the extreme right. Who is sitting in the middle?",
        "option_a": "B",
        "option_b": "A",
        "option_c": "E",
        "option_d": "C",
        "answer": "option_a",
        "difficulty": "Medium",
        "explanation": "Arrangement from left to right: C - E - B - A - D. The person in the middle (3rd spot) is B."
    },
    {
        "id": 17,
        "section": "Aptitude",
        "category": "logical",
        "topic": "Syllogisms",
        "question": "Statements: All algorithms are programs. Some programs are bugs. Conclusions: I. Some algorithms are bugs. II. No algorithm is a bug.",
        "option_a": "Only I follows",
        "option_b": "Only II follows",
        "option_c": "Either I or II follows",
        "option_d": "Neither I nor II follows",
        "answer": "option_c",
        "difficulty": "Medium",
        "explanation": "They form a complementary pair ('Some' and 'No'), so Either I or II follows."
    },
    {
        "id": 18,
        "section": "Aptitude",
        "category": "logical",
        "topic": "Puzzles",
        "question": "Four boxes Red, Blue, Green, Yellow are placed one above another. Red is not at the top. Green is immediately above Yellow. Blue is at the bottom. Which box is at the top?",
        "option_a": "Green",
        "option_b": "Red",
        "option_c": "Yellow",
        "option_d": "Blue",
        "answer": "option_a",
        "difficulty": "Hard",
        "explanation": "Bottom is Blue (Position 1). Green is immediately above Yellow (Positions 3 & 2). Top (Position 4) must be Red or Green. Red can't be top, so Green is top (Position 4), Yellow (3), Red (2), Blue (1)."
    },
    {
        "id": 19,
        "section": "Aptitude",
        "category": "logical",
        "topic": "Calendar & Clock",
        "question": "If 1st January 2024 was a Monday, what day of the week was 1st January 2025? (Note: 2024 is a leap year)",
        "option_a": "Tuesday",
        "option_b": "Wednesday",
        "option_c": "Thursday",
        "option_d": "Monday",
        "answer": "option_b",
        "difficulty": "Medium",
        "explanation": "A leap year has 366 days = 52 weeks + 2 odd days. Monday + 2 days = Wednesday."
    },

    # =========================================================================
    # --- VERBAL ABILITY ---
    # =========================================================================
    {
        "id": 20,
        "section": "Aptitude",
        "category": "verbal",
        "topic": "Grammar",
        "question": "Correct the highlighted error: 'He going to school every morning by bus.'",
        "option_a": "He goes to school every morning by bus.",
        "option_b": "He is gone to school every morning by bus.",
        "option_c": "He go to school every morning by bus.",
        "option_d": "He has going to school every morning by bus.",
        "answer": "option_a",
        "difficulty": "Easy",
        "explanation": "Habitual actions in simple present tense require 'goes' for third-person singular (He goes)."
    },
    {
        "id": 21,
        "section": "Aptitude",
        "category": "verbal",
        "topic": "Grammar",
        "question": "Choose the correct conjunction: 'I prefer tea _____ coffee.'",
        "option_a": "than",
        "option_b": "to",
        "option_c": "over than",
        "option_d": "from",
        "answer": "option_b",
        "difficulty": "Easy",
        "explanation": "The verb 'prefer' takes the preposition/conjunction 'to', not 'than'."
    },
    {
        "id": 22,
        "section": "Aptitude",
        "category": "verbal",
        "topic": "Vocabulary",
        "question": "Select the Synonym for the word: PRAGMATIC",
        "option_a": "Theoretical",
        "option_b": "Realistic",
        "option_c": "Idealistic",
        "option_d": "Arrogant",
        "answer": "option_b",
        "difficulty": "Medium",
        "explanation": "Pragmatic means dealing with things sensibly and realistically based on practical considerations."
    },
    {
        "id": 23,
        "section": "Aptitude",
        "category": "verbal",
        "topic": "Vocabulary",
        "question": "Select the Antonym for the word: METICULOUS",
        "option_a": "Precise",
        "option_b": "Careless",
        "option_c": "Fastidious",
        "option_d": "Methodical",
        "answer": "option_b",
        "difficulty": "Easy",
        "explanation": "Meticulous means extremely careful and precise; its antonym is careless."
    },
    {
        "id": 24,
        "section": "Aptitude",
        "category": "verbal",
        "topic": "Sentence and Paragraph Arrangement",
        "question": "Rearrange the jumbled parts to form a coherent sentence: (P) store / (Q) he / (R) went / (S) to the",
        "option_a": "Q - R - S - P",
        "option_b": "P - Q - R - S",
        "option_c": "S - P - Q - R",
        "option_d": "Q - S - P - R",
        "answer": "option_a",
        "difficulty": "Easy",
        "explanation": "Q (He) + R (went) + S (to the) + P (store) => 'He went to the store'."
    },
    {
        "id": 25,
        "section": "Aptitude",
        "category": "verbal",
        "topic": "Reading Comprehension",
        "question": "Passage: 'Artificial Intelligence is revolutionizing campus recruitment. Automated screening algorithms filter thousands of resumes in seconds based on skill keywords.' What is the main idea?",
        "option_a": "Resumes are obsolete.",
        "option_b": "AI algorithms speed up resume screening in hiring.",
        "option_c": "Students should not apply online.",
        "option_d": "AI replaces human recruiters completely.",
        "answer": "option_b",
        "difficulty": "Easy",
        "explanation": "The main passage idea focuses on AI revolutionizing and speeding up resume screening."
    },

    # =========================================================================
    # --- DSA PROBLEMS (LeetCode Style) ---
    # =========================================================================
    {
        "id": 26,
        "section": "Technical",
        "category": "dsa",
        "topic": "Arrays & Hashing",
        "question": "Two Sum: Given an array of integers `nums` and an integer `target`, return indices of the two numbers such that they add up to `target`.",
        "option_a": "O(N)",
        "option_b": "O(N^2)",
        "option_c": "O(N log N)",
        "option_d": "O(1)",
        "answer": "option_a",
        "difficulty": "Easy",
        "explanation": "Using a Hash Map to store elements allows checking `target - num` in O(1) time, yielding O(N) overall runtime.",
        "code_template_cpp": "class Solution {\npublic:\n    vector<int> twoSum(vector<int>& nums, int target) {\n        // Write your solution here\n        unordered_map<int, int> mp;\n        for(int i=0; i<nums.size(); i++) {\n            int comp = target - nums[i];\n            if(mp.count(comp)) return {mp[comp], i};\n            mp[nums[i]] = i;\n        }\n        return {};\n    }\n};",
        "code_template_py": "def twoSum(nums, target):\n    # Write your solution here\n    seen = {}\n    for i, num in enumerate(nums):\n        comp = target - num\n        if comp in seen:\n            return [seen[comp], i]\n        seen[num] = i\n    return []",
        "code_template_java": "class Solution {\n    public int[] twoSum(int[] nums, int target) {\n        Map<Integer, Integer> map = new HashMap<>();\n        for (int i = 0; i < nums.length; i++) {\n            int comp = target - nums[i];\n            if (map.containsKey(comp)) return new int[] { map.get(comp), i };\n            map.put(nums[i], i);\n        }\n        return new int[]{};\n    }\n}",
        "sample_input": "nums = [2, 7, 11, 15], target = 9",
        "expected_output": "[0, 1]"
    },
    {
        "id": 27,
        "section": "Technical",
        "category": "dsa",
        "topic": "Trees & Graphs",
        "question": "Binary Tree Level Order Traversal: Given the root of a binary tree, return the level order traversal of its nodes' values (i.e., from left to right, level by level). Which queue-based algorithm is optimal?",
        "option_a": "Breadth First Search (BFS)",
        "option_b": "Depth First Search (DFS)",
        "option_c": "Dijkstra's Algorithm",
        "option_d": "Kruskal's MST",
        "answer": "option_a",
        "difficulty": "Medium",
        "explanation": "BFS using a FIFO Queue naturally processes nodes level by level in O(N) time.",
        "code_template_cpp": "class Solution {\npublic:\n    vector<vector<int>> levelOrder(TreeNode* root) {\n        // BFS level order implementation\n    }\n};",
        "code_template_py": "def levelOrder(root):\n    # BFS level order implementation\n    pass",
        "code_template_java": "class Solution {\n    public List<List<Integer>> levelOrder(TreeNode root) {\n        // BFS implementation\n    }\n}",
        "sample_input": "root = [3, 9, 20, null, null, 15, 7]",
        "expected_output": "[[3], [9, 20], [15, 7]]"
    },
    {
        "id": 28,
        "section": "Technical",
        "category": "dsa",
        "topic": "Dynamic Programming",
        "question": "Climbing Stairs: You are climbing a staircase. It takes `n` steps to reach the top. Each time you can either climb 1 or 2 steps. In how many distinct ways can you climb to the top?",
        "option_a": "Fibonacci Sequence: dp[n] = dp[n-1] + dp[n-2]",
        "option_b": "Factorial: n!",
        "option_c": "Powers of 2: 2^n",
        "option_d": "n * (n - 1) / 2",
        "answer": "option_a",
        "difficulty": "Easy",
        "explanation": "To reach step n, you come from step n-1 or n-2. Thus dp[n] = dp[n-1] + dp[n-2], matching Fibonacci.",
        "code_template_cpp": "class Solution {\npublic:\n    int climbStairs(int n) {\n        if(n <= 2) return n;\n        int a = 1, b = 2;\n        for(int i = 3; i <= n; i++) {\n            int c = a + b;\n            a = b;\n            b = c;\n        }\n        return b;\n    }\n};",
        "code_template_py": "def climbStairs(n):\n    if n <= 2: return n\n    a, b = 1, 2\n    for _ in range(3, n + 1):\n        a, b = b, a + b\n    return b",
        "code_template_java": "class Solution {\n    public int climbStairs(int n) {\n        if (n <= 2) return n;\n        int a = 1, b = 2;\n        for (int i = 3; i <= n; i++) {\n            int c = a + b;\n            a = b; b = c;\n        }\n        return b;\n    }\n}",
        "sample_input": "n = 5",
        "expected_output": "8"
    },

    # =========================================================================
    # --- PROGRAMMING QUESTIONS (Code Now) ---
    # =========================================================================
    {
        "id": 29,
        "section": "Technical",
        "category": "programming",
        "topic": "String Manipulation",
        "question": "Palindrome Check: Write a function to check if a given string `s` is a palindrome (reads the same forward and backward, ignoring non-alphanumeric characters and case).",
        "option_a": "Two Pointer approach O(N)",
        "option_b": "Nested loops O(N^2)",
        "option_c": "Sorting O(N log N)",
        "option_d": "Stack only O(N)",
        "answer": "option_a",
        "difficulty": "Easy",
        "explanation": "Use two pointers starting at the beginning and end of the string, skipping non-alphanumeric characters.",
        "code_template_py": "def isPalindrome(s):\n    cleaned = ''.join(c.lower() for c in s if c.isalnum())\n    return cleaned == cleaned[::-1]",
        "code_template_cpp": "bool isPalindrome(string s) {\n    int l = 0, r = s.length() - 1;\n    while(l < r) {\n        while(l < r && !isalnum(s[l])) l++;\n        while(l < r && !isalnum(s[r])) r--;\n        if(tolower(s[l]) != tolower(s[r])) return false;\n        l++; r--;\n    }\n    return true;\n}",
        "code_template_java": "public boolean isPalindrome(String s) {\n    String clean = s.replaceAll(\"[^a-zA-Z0-9]\", \"\").toLowerCase();\n    return clean.equals(new StringBuilder(clean).reverse().toString());\n}",
        "sample_input": "s = 'A man, a plan, a canal: Panama'",
        "expected_output": "True"
    },

    # =========================================================================
    # --- CORE CS MCQS ---
    # =========================================================================
    {
        "id": 30,
        "section": "Technical",
        "category": "core_cs",
        "topic": "Operating Systems",
        "question": "Which of the following conditions is NOT required for a Deadlock to occur in an operating system?",
        "option_a": "Mutual Exclusion",
        "option_b": "Hold and Wait",
        "option_c": "Preemption allowed",
        "option_d": "Circular Wait",
        "answer": "option_c",
        "difficulty": "Medium",
        "explanation": "Coffman conditions for deadlock: 1. Mutual Exclusion, 2. Hold & Wait, 3. No Preemption (allowing preemption prevents deadlocks!), 4. Circular Wait."
    },
    {
        "id": 31,
        "section": "Technical",
        "category": "core_cs",
        "topic": "DBMS",
        "question": "In SQL, which clause is used to filter aggregated records produced by a `GROUP BY` statement?",
        "option_a": "WHERE",
        "option_b": "HAVING",
        "option_c": "ORDER BY",
        "option_d": "FILTER",
        "answer": "option_b",
        "difficulty": "Easy",
        "explanation": "`HAVING` filters aggregated groups after `GROUP BY`, whereas `WHERE` filters individual rows beforehand."
    },
    {
        "id": 32,
        "section": "Technical",
        "category": "core_cs",
        "topic": "Computer Networks",
        "question": "At which layer of the OSI model does the Internet Protocol (IP) operate?",
        "option_a": "Data Link Layer",
        "option_b": "Network Layer",
        "option_c": "Transport Layer",
        "option_d": "Application Layer",
        "answer": "option_b",
        "difficulty": "Easy",
        "explanation": "IP operates at Layer 3 (Network Layer) of the OSI model."
    },
    {
        "id": 33,
        "section": "Technical",
        "category": "core_cs",
        "topic": "Object Oriented Programming",
        "question": "What is the concept called when a subclass provides a specific implementation of a method that is already defined in its superclass?",
        "option_a": "Method Overloading",
        "option_b": "Method Overriding",
        "option_c": "Abstraction",
        "option_d": "Encapsulation",
        "answer": "option_b",
        "difficulty": "Easy",
        "explanation": "Method Overriding occurs when a subclass redefines a parent class method with the exact same signature (runtime polymorphism)."
    }
]

df = pd.DataFrame(questions_data)
df.to_excel("questions.xlsx", index=False)
print(f"Successfully generated expanded questions.xlsx with {len(df)} questions!")
